python -m trainers.semi_supervised_full \
  --dataset "cityscapes" \
  --data-path "dataset/cityscapes" \
  --val-interval 5000 \
  --num-labeled 150 \
  --model "reconet" \
  --reco  \
  --reco-weight 1.0 \
  --reco-temp 0.5 \
  --reco-num-queries 256 \
  --reco-num-negatives 256 \
  --reco-threshold 0.97 \
