python3 trainers/semi_supervised_full.py \
  --dataset "cityscapes" \
  --data-path "/local/home/sanjee23/dev/ReCo/dataset/cityscapes" \
  --val-interval 5000 \
  --num-labeled 150 \
  --model "reconet" \
  --reco  \
  --reco-weight 1.0 \
  --reco-temp 0.5 \
  --reco-num-queries 256 \
  --reco-num-negatives 256 \
  --reco-threshold 0.97 \